---
# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
jenkins_version: "2.176"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"


jenkins_plugins:
  - ace-editor
  - antisamy-markup-formatter
  - ant
  - apache-httpcomponents-client-4-api
  - authentication-tokens
  - badge
  - bouncycastle
  - branch-api
  - build-pipeline-plugin
  - built-on-column
  - cloudbees-folder
  - command-launcher
  - conditional-buildstep
  - config-file-provider
  - configuration-as-code
  - credentials-binding
  - credentials
  - dashboard-view
  - display-url-api
  - docker-commons
  - docker-workflow
  - durable-task
  - envinject-api
  - envinject
  - external-monitor-job
  - git-client
  - git
  - git-server
  - groovy-events-listener-plugin
  - groovy-events-listener-plugin-master
  - groovy
  - groovy-label-assignment
  - groovy-postbuild
  - groovy-remote
  - handlebars
  - jackson2-api
  - jacoco  
  - javadoc
  - jdk-tool
  - jenkins-multijob-plugin
  - job-dsl
  - jquery-detached
  - jquery
  - jsch
  - junit
  - ldap
  - lockable-resources
  - mailer
  - matrix-auth
  - matrix-project
  - maven-plugin
  - momentjs
  - nexus-artifact-uploader
  - nexus-jenkins-plugin  
  - pam-auth
  - parameterized-trigger
  - pipeline-build-step
  - pipeline-graph-analysis
  - pipeline-input-step
  - pipeline-milestone-step
  - pipeline-model-api
  - pipeline-model-declarative-agent
  - pipeline-model-definition
  - pipeline-model-extensions
  - pipeline-multibranch-defaults
  - pipeline-rest-api
  - pipeline-stage-step
  - pipeline-stage-tags-metadata
  - pipeline-stage-view
  - plain-credentials
  - run-condition
  - scm-api
  - script-security
  - shared-objects
  - shared-workspace
  - sonar
  - sonar-quality-gates
  - ssh-credentials
  - structs
  - token-macro
  - view-job-filters
  - windows-slaves
  - workflow-aggregator
  - workflow-api
  - workflow-basic-steps
  - workflow-cps-global-lib
  - workflow-cps
  - workflow-durable-task-step
  - workflow-job
  - workflow-multibranch
  - workflow-scm-step
  - workflow-step-api
  - workflow-support
  - pipeline
  - GitHub Integration Plugin

jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: true
jenkins_updates_url: "https://updates.jenkins.io"

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"
