---
# Optional method of pinning a specific version of Jenkins and/or overriding the
# default Jenkins packaging URL.
# jenkins_version: "1.644"
# jenkins_pkg_url: "https://www.example.com"

# Change this to `latest` to update Jenkins if a newer version is available.
jenkins_package_state: present

jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_home: /var/lib/jenkins
jenkins_hostname: localhost
jenkins_http_port: 8080
jenkins_jar_location: /opt/jenkins-cli.jar
jenkins_url_prefix: ""
jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

jenkins_plugins:
  - git
  - pipeline
  - pipeline-milestone-step
  - jackson2-api
  - pipeline-input-step
  - pipeline-graph-analysis
  - pipeline-rest-api
  - handlebars
  - momentjs
  - pipeline-stage-step
  - pipeline-stage-view
  - pipeline-stage-tags-metadata
  - plain-credentials
  - credentials-binding
  - pipeline-model-api
  - pipeline-model-declarative-agent
  - git-server
  - shared-objects
  - shared-workspace
  - groovy
  - groovy-remote
  - groovy-postbuild
  - groovy-label-assignment
  - groovy-events-listener-plugin
  - groovy-events-listener-plugin-master
  - authentication-tokens
  - docker-commons
  - durable-task
  - pipeline-stage-tags-metadata
  - lockable-resources
  - pipeline
  - matrix-project
  - junit
  - workflow-api
  - scm-api
  - git-client
  - jsch
  - ssh-credentials
  - credentials
  - workflow-scm-step
  - workflow-step-api
  - workflow-multibranch
  - nexus-artifact-uploader
  - Pipeline
  - pipeline-stage-step
  - pipeline-multibranch-defaults
  - dashboard-view
  - view-job-filters
  - job-dsl
  - build-pipeline-plugin
  - jenkins-multijob-plugin
  - build-pipeline-plugin
  - sonar-quality-gates
  - codescanner  

jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: true
jenkins_updates_url: "https://updates.jenkins.io"

jenkins_admin_username: admin
jenkins_admin_password: admin
jenkins_admin_password_file: ""

jenkins_process_user: jenkins
jenkins_process_group: "{{ jenkins_process_user }}"

jenkins_init_changes:
  - option: "JENKINS_ARGS"
    value: "--prefix={{ jenkins_url_prefix }}"
  - option: "{{ jenkins_java_options_env_var }}"
    value: "{{ jenkins_java_options }}"
