jenkins:
    systemMessage: "Welcome to Jenkins Config"    
    authorizationStrategy: "loggedInUsersCanDoAnything"
    disableRememberMe: false
    markupFormatter: "plainText"
    mode: NORMAL
    myViewsTabBar: "standard"
    securityRealm:
      local:
        allowsSignup: false
        users:
          - id: "admin_casc"
            password: "somethingsecret"
security:
    apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
    downloadSettings:
        useBrowser: false
    globalJobDslSecurityConfiguration:
        useScriptSecurity: true
    sSHD:
        port: -1
unclassified:
  badgePlugin:
    disableFormatHTML: false
  casCGlobalConfig:
    configurationPath: "/var/lib/jenkins/jenkins.yaml"
  gitSCM:
    createAccountBasedOnEmail: false
  globalEventsPlugin:
    disableSynchronization: false
    onEventGroovyCode: "log.info(\"Fired event '${event}'.\")"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
  mailer:
    adminAddress: "address not configured yet <nobody@nowhere>"
    charset: "UTF-8"
    useSsl: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations: 
      - name: sonarqube 
        serverUrl: http://localhost:9000/sq
        additionalAnalysisProperties:
        additionalProperties:
        triggers:
tool:
  ant:
    defaultProperties:
    - installSource:
        installers:
        - "antFromApache"
  maven:
    settingsProvider:
      filePath:
        path: /usr/share/maven-settings.xml
    installations:
    - name: "maven"
      home: /usr/share/maven
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.5.0"        
  git:
    installations:
    - home: "/usr/bin/git"
      name: "git"
  groovyInstallation:
    defaultProperties:
    - installSource:
        installers:
        - "groovyInstaller"
  jdk:
    installations:      
    - name: "Java"
      home: "/usr/lib/jvm/java-8-openjdk-amd64/"    
    #defaultProperties:
    #- installSource:
    #installers:
    # - jdkInstaller:
    #acceptLicense: false
  #maven:
    #defaultProperties:
    #- installSource:
        #installers:
        #- "maven"
  msBuildSQRunnerInstallation:
    defaultProperties:
    - installSource:
        installers:
        - "msBuildSonarQubeRunnerInstaller"
  sonarRunnerInstallation:
    defaultProperties:
    - installSource:
        installers:
        - "sonarRunnerInstaller"
jobs:
  - script: >
      folder('testjobs')
  - script: >
      pipelineJob('testjobs/default-agent') {
        definition {
          cps {
            script("""\
              pipeline {
                agent any
                stages {
                  stage ('test') {
                    steps {
                      echo "hello"
                    }
                  }
                }
              }""".stripIndent())
          }
        }
      }          
